"""
Multimodal Classification Inference Module
===========================================
UPMC Food-101 — 101 food categories
Models:
  - clip_zero_shot : CLIP (ViT-B/32) with standard prompt templates
  - clip_few_shot  : CLIP image features + trained LogisticRegression probe

Requires:
  pip install transformers

For few-shot inference, the trained classifier must exist at:
  Model/Multimodal_Model/food101_fewshot.pkl
  (generated by run_few_shot_final() in the training notebook)
"""

import io
import time
import logging
from pathlib import Path

import torch
import torch.nn.functional as F
from PIL import Image

logger = logging.getLogger(__name__)

# ── Device ────────────────────────────────────────────────────────────
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
logger.info("Multimodal classifier using device: %s", DEVICE)

# ── Paths ─────────────────────────────────────────────────────────────
_PROJECT_ROOT = Path(__file__).resolve().parents[3]
_FEW_SHOT_CLF_PATH = _PROJECT_ROOT / "models" / "multimodal_dataset" / "food101_fewshot.pkl"

MODEL_REGISTRY = {
    "clip_zero_shot": {"method": "zero_shot",  "backbone": "openai/clip-vit-base-patch32"},
    "clip_few_shot":  {"method": "few_shot",   "backbone": "openai/clip-vit-base-patch32"},
}

# UPMC Food-101 class names — sorted alphabetically (matches os.listdir + sorted() in notebook)
FOOD101_CLASSES = [
    "apple_pie", "baby_back_ribs", "baklava", "beef_carpaccio", "beef_tartare",
    "beet_salad", "beignets", "bibimbap", "bread_pudding", "breakfast_burrito",
    "bruschetta", "caesar_salad", "cannoli", "caprese_salad", "carrot_cake",
    "ceviche", "cheese_plate", "cheesecake", "chicken_curry", "chicken_quesadilla",
    "chicken_wings", "chocolate_cake", "chocolate_mousse", "churros", "clam_chowder",
    "club_sandwich", "crab_cakes", "creme_brulee", "croque_madame", "cup_cakes",
    "deviled_eggs", "donuts", "dumplings", "edamame", "eggs_benedict",
    "escargots", "falafel", "filet_mignon", "fish_and_chips", "foie_gras",
    "french_fries", "french_onion_soup", "french_toast", "fried_calamari", "fried_rice",
    "frozen_yogurt", "garlic_bread", "gnocchi", "greek_salad", "grilled_cheese_sandwich",
    "grilled_salmon", "guacamole", "gyoza", "hamburger", "hot_and_sour_soup",
    "hot_dog", "huevos_rancheros", "hummus", "ice_cream", "lasagna",
    "lobster_bisque", "lobster_roll_sandwich", "macaroni_and_cheese", "macarons", "miso_soup",
    "mussels", "nachos", "omelette", "onion_rings", "oysters",
    "pad_thai", "paella", "pancakes", "panna_cotta", "peking_duck",
    "pho", "pizza", "pork_chop", "poutine", "prime_rib",
    "pulled_pork_sandwich", "ramen", "ravioli", "red_velvet_cake", "risotto",
    "samosa", "sashimi", "scallops", "seaweed_salad", "shrimp_and_grits",
    "spaghetti_bolognese", "spaghetti_carbonara", "spring_rolls", "steak", "strawberry_shortcake",
    "sushi", "tacos", "takoyaki", "tiramisu", "tuna_tartare", "waffles",
]

# Standard prompt template used during zero-shot training
_ZERO_SHOT_PROMPTS = [
    f"A photo of {c.replace('_', ' ')}, a type of food"
    for c in FOOD101_CLASSES
]


class MultimodalClassifier:
    """CLIP-based zero-shot and few-shot classifier for UPMC Food-101."""

    def __init__(self):
        self._clip_model       = None
        self._processor        = None
        self._text_features    = None   # pre-computed, cached after first load
        self._few_shot_clf     = None   # sklearn LogisticRegression or None
        self._available = list(MODEL_REGISTRY.keys())
        logger.info("MultimodalClassifier initialised. Available models: %s", self._available)

    @property
    def available_models(self) -> list[str]:
        return self._available

    # ── CLIP backbone ──────────────────────────────────────────────────
    def _ensure_clip_loaded(self) -> bool:
        if self._clip_model is not None:
            return True
        try:
            from transformers import CLIPModel, CLIPProcessor
        except ImportError:
            logger.error("'transformers' package is not installed.")
            return False

        backbone = MODEL_REGISTRY["clip_zero_shot"]["backbone"]
        logger.info("Loading CLIP backbone '%s' …", backbone)
        self._processor  = CLIPProcessor.from_pretrained(backbone)
        self._clip_model = CLIPModel.from_pretrained(backbone)
        self._clip_model.to(DEVICE)
        self._clip_model.eval()

        # Pre-compute and cache normalised text features for all 101 classes
        logger.info("Pre-computing text features for %d classes on %s …", len(FOOD101_CLASSES), DEVICE)
        with torch.no_grad():
            inputs = self._processor(
                text=_ZERO_SHOT_PROMPTS,
                return_tensors="pt",
                padding=True,
                truncation=True,
                max_length=77,
            )
            inputs = {k: v.to(DEVICE) for k, v in inputs.items()}
            text_out = self._clip_model.text_model(
                input_ids=inputs.get("input_ids"),
                attention_mask=inputs.get("attention_mask"),
            )
            feats = self._clip_model.text_projection(text_out.pooler_output)
            self._text_features = F.normalize(feats, p=2, dim=-1)   # [101, 512]

        logger.info("CLIP ready on %s. Text features shape: %s", DEVICE, tuple(self._text_features.shape))
        return True

    # ── Few-shot probe ─────────────────────────────────────────────────
    def _ensure_few_shot_loaded(self) -> None:
        if self._few_shot_clf is not None:
            return
        if not _FEW_SHOT_CLF_PATH.exists():
            logger.warning(
                "Few-shot classifier not found at '%s'. "
                "Run run_few_shot_final() in the training notebook to generate it. "
                "Falling back to zero-shot for this request.",
                _FEW_SHOT_CLF_PATH,
            )
            return
        try:
            import joblib
            self._few_shot_clf = joblib.load(str(_FEW_SHOT_CLF_PATH))
            logger.info("Few-shot classifier loaded from %s", _FEW_SHOT_CLF_PATH)
        except Exception as exc:
            logger.error("Failed to load few-shot classifier: %s", exc)

    # ── Model entry-point ──────────────────────────────────────────────
    def load_model(self, name: str) -> bool:
        """Load the requested model into memory. Returns True on success."""
        if name not in MODEL_REGISTRY:
            logger.error("Unknown multimodal model '%s'", name)
            return False
        if not self._ensure_clip_loaded():
            return False
        if name == "clip_few_shot":
            self._ensure_few_shot_loaded()
        return True

    # ── Inference ──────────────────────────────────────────────────────
    def _extract_image_feature(self, image_bytes: bytes) -> torch.Tensor:
        """Return a normalised CLIP image feature vector [1, 512]."""
        img = Image.open(io.BytesIO(image_bytes)).convert("RGB")
        inputs = self._processor(images=img, return_tensors="pt")
        inputs = {k: v.to(DEVICE) for k, v in inputs.items()}
        with torch.no_grad():
            image_out = self._clip_model.vision_model(pixel_values=inputs["pixel_values"])
            feat = self._clip_model.visual_projection(image_out.pooler_output)
        return F.normalize(feat, p=2, dim=-1)

    def predict(self, image_bytes: bytes, text_query: str, model_name: str) -> dict:
        """
        Run multimodal inference.

        For zero-shot  : cosine similarity between image feature and 101 text class features.
        For few-shot   : CLIP image feature fed into the trained LogisticRegression probe.
                         Falls back to zero-shot if the pkl file is missing.

        Returns:
            {
              "model": str,
              "method": str,
              "text_query": str,
              "predictions": [{"label": str, "confidence": float}, ...],
              "inference_time_ms": float,
            }
        """
        if not self._ensure_clip_loaded():
            raise RuntimeError("CLIP model could not be loaded")

        start = time.perf_counter()
        img_feat = self._extract_image_feature(image_bytes)   # [1, 512]
        method   = MODEL_REGISTRY[model_name]["method"]

        # ── Few-shot path ──────────────────────────────────────────────
        if model_name == "clip_few_shot":
            self._ensure_few_shot_loaded()

        if model_name == "clip_few_shot" and self._few_shot_clf is not None:
            feat_np   = img_feat.cpu().numpy()                           # [1, 512]
            probs_np  = self._few_shot_clf.predict_proba(feat_np)[0]    # [n_classes]
            classes   = list(self._few_shot_clf.classes_)
            sorted_idx = sorted(range(len(probs_np)), key=lambda i: probs_np[i], reverse=True)
            predictions = [
                {"label": classes[i], "confidence": round(float(probs_np[i]), 4)}
                for i in sorted_idx
            ]

        # ── Zero-shot path (default / fallback) ───────────────────────
        else:
            method  = "zero_shot"
            logits  = 100.0 * (img_feat @ self._text_features.T)   # [1, 101]
            probs   = torch.softmax(logits, dim=-1)[0]              # [101]
            sorted_idx = probs.argsort(descending=True).tolist()
            predictions = [
                {"label": FOOD101_CLASSES[i], "confidence": round(probs[i].item(), 4)}
                for i in sorted_idx
            ]

        elapsed = (time.perf_counter() - start) * 1000

        return {
            "model": model_name,
            "method": method,
            "text_query": text_query,
            "predictions": predictions,
            "inference_time_ms": round(elapsed, 2),
        }
